- hosts: localhost

  vars:
    - my_name: "hdldump"
    - my_file: "install_{{ my_name }}"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - make
      - gcc
      - coreutils

  - name: "{{ my_name }} - Generate scripts"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - build source"
    command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      creates: "/usr/local/bin/hdldump"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "hdldump"
    module_state: "present"