# Dependencies
- import_playbook: install_samba.yml
- import_playbook: install_romdir.yml
- import_playbook: install_extradirs.yml

- hosts: localhost

  vars:
    - my_name: "Recalbox CIFS"
    - my_file: "install_recalbox_cifs"

    - top_level_paths:
      - { name: "ROMS", enabled: "yes",  generic: "roms", systems: "yes" }
      - { name: "SAVES", enabled: "yes",  generic: "saves", systems: "yes"  }
      - { name: "BIOS", enabled: "yes",  generic: "bios", systems: "yes"  }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build top level"
    file:
      path: "{{ retronas_path }}/recalbox"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Restart service"

  - name: "get facts for path"
    stat:
      path: "{{ retronas_path }}/recalbox/{{ item.recalbox }}"
    with_items:
      - "{{ system_map }}"
    register: recalbox_stat

  - name: "{{ my_name }} - build top level share paths"
    file:
      path: "{{ retronas_path }}/recalbox/{{ item.name }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    with_items:
      "{{ top_level_paths }}"
    when: 
      - item.enabled == "yes"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build systems directory layout"
    file:
      src: "../../{{ item.1.generic|lower }}/{{ item.0.src }}"
      dest: "{{ retronas_path }}/recalbox/{{ item.1.name }}/{{ item.0.recalbox }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
    with_nested:
      - "{{ system_map }}"
      - "{{ top_level_paths }}"
    when: 
      - item.1.enabled == "yes"
      - item.0.recalbox | length > 0
      - item.1.systems == "yes"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: recalbox
      option: "include"
      value: "/etc/samba/retronas_recalbox.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_recalbox.conf.j2"
      dest: /etc/samba/retronas_recalbox.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "recalbox_cifs"
    module_state: "present"