- hosts: localhost

  vars:
    - my_name: "Samba"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - install from repos"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - avahi-daemon
      - samba
      - samba-vfs-modules

  - name: "{{ my_name }} - configure retro protocols"
    ini_file: 
      path: /etc/samba/smb.conf
      section: global
      option: "min protocol"
      value: "CORE"

  - name: "{{ my_name }} - netbios name"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "netbios name"
      value: "retrosmb"

  - name: "{{ my_name }} - lanman auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "lanman auth"
      value: "yes"

  - name: "{{ my_name }} - client lanman auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "client lanman auth"
      value: "yes"

  - name: "{{ my_name }} - ntlm auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "ntlm auth"
      value: "yes"

  - name: "{{ my_name }} - client ntlm auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "client ntlm auth"
      value: "yes"

  - name: "{{ my_name }} - ntlmv2 auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "ntlmv2 auth"
      value: "yes"

  - name: "{{ my_name }} - client ntlmv2 auth"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "client ntlmv2 auth"
      value: "yes"

  - name: "{{ my_name }} - unix extensions"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "unix extensions"
      value: "no"

  - name: "{{ my_name }} - allow insecure wide links"
    ini_file:
      path: /etc/samba/smb.conf
      section: global
      option: "allow insecure wide links"
      value: "yes"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: retronas
      option: "include"
      value: "/etc/samba/retronas.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: templates/install_samba/retronas.conf.j2
      dest: /etc/samba/retronas.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - avahi-daemon
      - smbd
      - nmbd

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - avahi-daemon
      - smbd
      - nmbd

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "samba"
    module_state: "present"