- hosts: localhost

  vars:
    - my_name: "Netatalk2.X"
    - my_file: "install_netatalk2x"

    - packages:
       - avahi-daemon
       - build-essential
       - make
       - automake
       - autoconf
       - libdb-dev
       - libdb++-dev
       - libavahi-common-dev
       - libavahi-client-dev
       - libavahi-core-dev
       - libdbus-1-dev
       - libssl-dev
       - autotools-dev
       - libtool
       - libcups2-dev
       - libavahi-client-dev
       - libgcrypt20-dev
       - expect
       - libltdl-dev

    - services:
      - avahi-daemon
      - atalkd
      - afpd
      - papd
      - timelord
      - a2boot

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }}  - unhold netatalk package"
    shell: "/usr/bin/apt-mark unhold netatalk"

  - name: "{{ my_name }}  - remove package-based Netatalk"
    apt:
       name: "{{ item }}"
       state: absent
    with_items:
       - netatalk

  - name: "{{ my_name }}  - install dependencies"
    apt:
       name: "{{ item }}"
       state: latest
    with_items: "{{ packages }}"


  - name: "{{ my_name }} - create install script"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: '0755'

  - name: "{{ my_name }} - install from source"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"

  - name: "{{ my_name }} - afpexpect.sh"
    template:
      src: "templates/{{ my_file }}/afpexpect.sh.j2"
      dest: "{{ retronas_root }}/bin/netatalk2x/bin/afpexpect.sh"
      owner: root
      group: root
      mode: '0754'

#  - name: "{{ my_name }} - configure /etc/default/netatalk"
#    template:
#      src: "templates/{{ my_file }}/default.j2"
#      dest: /etc/default/netatalk
#      owner: root
#      group: root
#      mode: '0644'
#    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - AppleVolumes.default"
    template:
      src: "templates/{{ my_file }}/AppleVolumes.default.j2"
      dest: "{{ retronas_root }}/bin/netatalk2x/etc/netatalk/AppleVolumes.default"
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"


  - name: "{{ my_name }} - afpd.conf"
    template:
      src: "templates/{{ my_file }}/afpd.conf.j2"
      dest: "{{ retronas_root }}/bin/netatalk2x/etc/netatalk/afpd.conf"
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - atalkd.conf"
    template:
      src: "templates/{{ my_file }}/atalkd.conf.j2"
      dest: "{{ retronas_root }}/bin/netatalk2x/etc/netatalk/atalkd.conf"
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ services }}"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items: "{{ services }}"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "netatalk2x"
    module_state: "present"