- hosts: localhost

  vars:
    - my_name: "NFS"
    - my_file: "install_nfs"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - install from repos"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - nfs-common
      - nfs-kernel-server

  - name: "{{ my_name }} - retrieve {{ retronas_user }} user info"
    getent:
      database: passwd
      key: "{{ retronas_user }}"

  - set_fact:
      retronas_user_id: "{{ getent_passwd[retronas_user][1] }}"

  - name: "{{ my_name }} - retrieve {{ retronas_group }} group info"
    getent:
      database: group
      key: "{{ retronas_group }}"

  - set_fact:
      retronas_group_id: "{{ getent_group[retronas_group][1] }}"

  - name: "{{ my_name }} - enable NFS v2 v3 v4"
    template:
      src: "templates/{{ my_file }}/default.j2"
      dest: /etc/default/nfs-kernel-server
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable NFS exports"
    template:
      src: "templates/{{ my_file }}/exports.j2"
      dest: /etc/exports
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - nfs-kernel-server

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - nfs-kernel-server

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "nfs"
    module_state: "present"