- hosts: localhost

  vars:
    - my_name: "Netatalk3"
    - my_file: "install_netatalk3"

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }}  - unhold netatalk package"
    shell: "/usr/bin/apt-mark unhold netatalk"

  - name: "{{ my_name }}  - install from repos"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
       - avahi-daemon
       - netatalk

  - name: "{{ my_name }}  - configure retro protocols"
    ini_file: 
      dest=/etc/netatalk/afp.conf
      section=Global
      option="uam list"
      value="uams_guest.so uams_clrtxt.so uams_dhx.so uams_dhx2.so"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }}  - configure hostname"
    ini_file: 
      dest=/etc/netatalk/afp.conf
      section=Global
      option="hostname"
      value="retroafp"
    notify: "{{ my_name }} - Restart service"
    
  - name: "{{ my_name }}  - configure mimic model"
    ini_file: 
      dest=/etc/netatalk/afp.conf
      section=Global
      option="mimic model"
      value="PowerMac"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }}  - configure Bonjour"
    ini_file: 
      dest=/etc/netatalk/afp.conf
      section=Global
      option="zeroconf"
      value="yes"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }}  - configure log level"
    ini_file:
      dest=/etc/netatalk/afp.conf
      section=Global
      option="log level"
      value="info"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }}  - configure log file"
    ini_file:
      dest=/etc/netatalk/afp.conf
      section=Global
      option="log file"
      value="/var/log/afp.log"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }}  - configure listen address"
    ini_file:
      dest=/etc/netatalk/afp.conf
      section=Global
      option="afp listen"
      value="0.0.0.0"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      dest=/etc/netatalk/afp.conf
      section=Global
      option="include"
      value="/etc/netatalk/retronas.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas.conf.j2"
      dest: /etc/netatalk/retronas.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - avahi-daemon
      - netatalk

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - avahi-daemon
      - netatalk

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "netatalk3"
    module_state: "present"