# Dependencies
- import_playbook: install_samba.yml
- import_playbook: install_romdir.yml

- hosts: localhost

  vars:
    - my_name: "EmuElec CIFS"
    - my_file: "install_emuelec_cifs"

    - internal_symlinks:
      - { src: 'nintendo/famicom', dest: 'nesh' }
      - { src: 'nintendo/gameboyadvance', dest: 'gbah' }
      - { src: 'nintendo/gameboy', dest: 'gbh' }
      - { src: 'nintendo/gameboycolor', dest: 'gbch' }      
      - { src: 'nintendo/superfamicom', dest: 'snesh' }
      - { src: 'sega/gamegear', dest: 'gamegearh' }
      - { src: 'sega/megadrive', dest: 'genh' }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build top level"
    file:
      path: "{{ retronas_path }}/emuelec"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Restart service"

  - name: "get facts for path"
    stat:
      path: "{{ retronas_path }}/emuelec/{{ item.emuelec }}"
    with_items:
      - "{{ system_map }}"
    register: emuelec_stat

  - name: "{{ my_name }} - build systems directory layout"
    file:
      src: "../roms/{{ item.src }}"
      dest: "{{ retronas_path }}/emuelec/{{ item.emuelec }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
    with_items:
      - "{{ system_map }}"
    when: 
      - item.emuelec | length > 0
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build internal hacks directory layout"
    file:
      src: "../roms/{{ item.src }}"
      dest: "{{ retronas_path }}/emuelec/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
    with_items:
      - "{{ internal_symlinks }}"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: emuelec
      option: "include"
      value: "/etc/samba/retronas_emuelec.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_emuelec.conf.j2"
      dest: /etc/samba/retronas_emuelec.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "emuelec_cifs"
    module_state: "present"