- hosts: localhost

  vars:
    - my_name: "nbd-client"
    - my_file: "install_nbd-client"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - install from repos"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - nbd-client

  - name: "{{ my_name }} - enable ndb kernel module"
    template:
      src: "templates/{{ my_file }}/nbd.conf.j2"
      dest: /etc/modules-load.d/nbd.conf
      owner: root
      group: root
      mode: '0644'

  - name: "{{ my_name }} - check module loaded"
    shell: "lsmod | grep nbd"
    args:
      warn: no 
    ignore_errors: yes
    register: module_loaded

  - name: "{{ my_name }} - enable ndb kernel module"
    command:
      args: 
        cmd: "modprobe nbd"
    when:
      module_loaded.failed != false

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "nbd-client"
    module_state: "present"