- hosts: localhost

  vars:
    - my_name: "pfsshell"
    - my_file: "install_pfsshell"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - make
      - gcc
      - coreutils
      - meson
      - ninja-build
      - libfuse-dev

  - name: "{{ my_name }} - install script"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: '0750'

  - name: "{{ my_name }} - build source"
    command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      creates: "/usr/local/bin/pfsfuse"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "pfsshell"
    module_state: "present"